version: 2.1

jobs:
  generate-wrapper:
    docker:
      - image: cimg/android:2025.05

    steps:
      - checkout

      - run:
          name: Generate Gradle Wrapper
          command: |
            gradle wrapper --gradle-version 8.7

      - store_artifacts:
          path: gradlew
          destination: gradlew

      - store_artifacts:
          path: gradlew.bat
          destination: gradlew.bat

      - store_artifacts:
          path: gradle/wrapper
          destination: gradle-wrapper

workflows:
  generate:
    jobs:
      - generate-wrapper